### ISSUE TITLE
Trying to extend function gpioWaveAddGeneric

### ISSUE THREAD

**Issue by MeisterPilaf** [go-pigpio/pigpio#1]
First of all i want to thank you for your work. 

I tried to extend your library but it does not work.

`func gpioWaveAddGeneric(numPulses uint, pulse *Pulse) (err error) {
        totalPulses := int(C.gpioWaveAddGeneric(C.unsigned(numPulses), &pulse[0]))
        if totalPulses > 0 {
                // totalPulses = the new total number of pulses in the current waveform if OK, otherwise PI_TOO_MANY_PULSES$
        } else {
                // handle erroer
                err = Errno(totalPulses)
        }
        return
}`

I got this error.

root@raspberrypi:/home/pi/go/src/pi/helloworld# go run main.go
# github.com/go-pigpio/pigpio/pigpio
/root/go/src/github.com/go-pigpio/pigpio/pigpio/pigpio.go:319:48: undefined: Pulse

Maybe you know what is wrong and can help me.

**Comment by MeisterPilaf** [comment]
> First of all i want to thank you for your work.
> 
> I tried to extend your library but it does not work.
> 
> `func gpioWaveAddGeneric(numPulses uint, pulse *Pulse) (err error) { totalPulses := int(C.gpioWaveAddGeneric(C.unsigned(numPulses), &pulse[0])) if totalPulses > 0 { // totalPulses = the new total number of pulses in the current waveform if OK, otherwise PI_TOO_MANY_PULSES$ } else { // handle erroer err = Errno(totalPulses) } return }`
> 
> I got this error.
> 
> `root@raspberrypi:/home/pi/go/src/pi/helloworld# go run main.go
> 
> # github.com/go-pigpio/pigpio/pigpio
> /root/go/src/github.com/go-pigpio/pigpio/pigpio/pigpio.go:319:48: undefined: Pulse`
> 
> Maybe you know what is wrong and can help me.

**Comment by kostix** [comment]
[SO thread](https://stackoverflow.com/q/58391519/720999) about the same matters.
